import type {
  Agent,
  Task,
  Review,
  SampleOutput,
  PricingTier,
  TaskMetric,
  TimelineEntry,
  CostSegment,
  KpiData,
  AgentCapability,
  PerformanceMetric,
  ReviewSummary,
} from "./types";

export const MOCK_AGENTS: Agent[] = [
  {
    id: "coder",
    name: "Coder",
    role: "Code Interpreter & GitHub Expert",
    initials: "C",
    gradientFrom: "#3B82F6",
    gradientTo: "#2563EB",
    successRate: 94,
    avgCost: 2.5,
    avgRuntime: "45s",
    totalTasks: 1247,
    weeklyPrice: 99,
    description:
      "This agent uses Python & GitHub APIs to write code, fix bugs, create pull requests, and run automated analysis. It has fixed 150 bugs, written 2000+ lines of production code, and maintains a 94% success rate across all tasks.",
    specialisation:
      "Python, JavaScript, TypeScript, Go. Full-stack development, bug fixes, code reviews, automated testing.",
    tools: ["Code Interpreter", "GitHub MCP", "Bash Terminal", "Web Search", "File I/O"],
    llmBackend: "Claude Sonnet (primary), with fallback to DeepSeek for code-heavy tasks.",
    available: true,
  },
  {
    id: "research",
    name: "Research",
    role: "Topic Investigation & Reports",
    initials: "R",
    gradientFrom: "#10B981",
    gradientTo: "#059669",
    successRate: 91,
    avgCost: 1.8,
    avgRuntime: "1m 20s",
    totalTasks: 892,
    weeklyPrice: 59,
    description:
      "Investigates topics, compiles reports, and provides citations. Excels at competitor analysis, market research, and technical documentation.",
    specialisation: "Web research, PDF analysis, data synthesis, report generation.",
    tools: ["Web Search", "PDF Reader", "File I/O"],
    llmBackend: "Claude Sonnet (primary), Gemini Flash for high-volume tasks.",
    available: true,
  },
  {
    id: "pm",
    name: "PM",
    role: "Product Manager & PRD Writer",
    initials: "PM",
    gradientFrom: "#F59E0B",
    gradientTo: "#D97706",
    successRate: 88,
    avgCost: 1.5,
    avgRuntime: "2m 10s",
    totalTasks: 456,
    weeklyPrice: 79,
    description: "Creates PRDs, manages backlogs, and writes user stories.",
    specialisation: "Product requirements, user stories, backlog management.",
    tools: ["Notion MCP", "Jira MCP", "Web Search"],
    llmBackend: "Claude Sonnet.",
    available: true,
  },
  {
    id: "qa",
    name: "QA",
    role: "Testing & Bug Detection",
    initials: "QA",
    gradientFrom: "#EF4444",
    gradientTo: "#DC2626",
    successRate: 92,
    avgCost: 2.0,
    avgRuntime: "1m 45s",
    totalTasks: 678,
    weeklyPrice: 89,
    description: "Runs automated tests, detects bugs, and generates test reports.",
    specialisation: "Playwright, Cypress, unit testing, regression testing.",
    tools: ["Code Interpreter", "Playwright", "Cypress"],
    llmBackend: "Claude Sonnet.",
    available: true,
  },
  {
    id: "copywriter",
    name: "Copywriter",
    role: "Marketing & Content Creation",
    initials: "CW",
    gradientFrom: "#8B5CF6",
    gradientTo: "#7C3AED",
    successRate: 90,
    avgCost: 1.2,
    avgRuntime: "35s",
    totalTasks: 1034,
    weeklyPrice: 69,
    description: "Writes marketing copy, blog posts, and email campaigns.",
    specialisation: "Content marketing, SEO writing, email campaigns.",
    tools: ["Web Search", "CMS APIs", "Email Tools"],
    llmBackend: "Claude Sonnet.",
    available: true,
  },
  {
    id: "image-design",
    name: "Image Design",
    role: "Graphics & Design Assets",
    initials: "ID",
    gradientFrom: "#EC4899",
    gradientTo: "#DB2777",
    successRate: null,
    avgCost: null,
    avgRuntime: null,
    totalTasks: 0,
    weeklyPrice: 0,
    description: "Creates images, logos, and design assets using AI generation.",
    specialisation: "Stable Diffusion, DALL-E, Midjourney integration.",
    tools: [],
    llmBackend: "TBD",
    available: false,
  },
  {
    id: "video-design",
    name: "Video Design",
    role: "Video Production & Editing",
    initials: "VD",
    gradientFrom: "#06B6D4",
    gradientTo: "#0891B2",
    successRate: null,
    avgCost: null,
    avgRuntime: null,
    totalTasks: 0,
    weeklyPrice: 0,
    description: "Produces and edits video content using AI tools.",
    specialisation: "RunwayML, Kling, Sora, FFmpeg integration.",
    tools: [],
    llmBackend: "TBD",
    available: false,
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "r1",
    author: "Alex M.",
    rating: 5,
    text: "Coder agent nailed the refactoring task. Clean code, well-documented PR, tests passing. Will hire again.",
    date: "2 days ago",
  },
  {
    id: "r2",
    author: "Sarah K.",
    rating: 4,
    text: "Good output overall. Missed one edge case in error handling but fixed it quickly on a follow-up task.",
    date: "5 days ago",
  },
  {
    id: "r3",
    author: "James T.",
    rating: 5,
    text: "Fantastic for repetitive coding tasks. Consistent quality, fast turnaround. Best $99/week I spend.",
    date: "1 week ago",
  },
];

export const MOCK_SAMPLE_OUTPUTS: SampleOutput[] = [
  {
    id: "s1",
    title: "Authentication Module Refactor",
    description:
      "Refactored OAuth2 flow, added refresh token rotation, and wrote 12 unit tests. Delivered as a GitHub PR.",
    status: "completed",
    cost: 3.2,
    runtime: "72s",
  },
  {
    id: "s2",
    title: "API Rate Limiter Implementation",
    description:
      "Built a sliding-window rate limiter with Redis backend. Included load testing results and documentation.",
    status: "completed",
    cost: 2.1,
    runtime: "55s",
  },
];

export const MOCK_PRICING_TIERS: PricingTier[] = [
  {
    name: "Solo",
    price: 99,
    period: "/week",
    features: ["1 Coder agent", "Unlimited tasks", "Standard priority", "Email support"],
    highlighted: false,
  },
  {
    name: "Small Team",
    price: 349,
    period: "/week",
    features: [
      "PM + Coder + QA agents",
      "Orchestrated workflows",
      "High priority",
      "Slack support",
    ],
    highlighted: true,
  },
  {
    name: "Full Squad",
    price: 999,
    period: "/week",
    features: [
      "5+ agents, orchestrated",
      "Custom workflows",
      "Dedicated support",
      "SLA guarantees",
    ],
    highlighted: false,
  },
];

export const MOCK_CAPABILITIES: AgentCapability[] = [
  { name: "Code Interpreter", description: "Execute Python and JavaScript in a sandboxed environment. Analyse, debug, and generate code.", icon: "lucide:code-2", colorClass: "text-primary", bgClass: "bg-primary/10" },
  { name: "GitHub MCP", description: "Create PRs, read repos, review diffs, and manage branches via Model Context Protocol.", icon: "lucide:github", colorClass: "text-success", bgClass: "bg-success/10" },
  { name: "Bash Terminal", description: "Run shell commands with safeguards. Install packages, run tests, manage files.", icon: "lucide:terminal", colorClass: "text-warning", bgClass: "bg-warning/10" },
  { name: "Web Search", description: "Search documentation, Stack Overflow, and APIs for up-to-date solutions.", icon: "lucide:search", colorClass: "text-[#8B5CF6]", bgClass: "bg-[#8B5CF6]/10" },
  { name: "File I/O", description: "Read, write, and manage project files. Parse logs, configs, and source code.", icon: "lucide:file-text", colorClass: "text-[#EC4899]", bgClass: "bg-[#EC4899]/10" },
  { name: "RAG Search", description: "Semantic search across past tasks and knowledge files for context-aware solutions.", icon: "lucide:database", colorClass: "text-[#14B8A6]", bgClass: "bg-[#14B8A6]/10" },
];

export const MOCK_USE_CASES: string[] = [
  "Bug Fixes",
  "Code Reviews",
  "Unit Tests",
  "API Integrations",
  "Refactoring",
  "Documentation",
  "Database Queries",
  "Security Audits",
];

export const MOCK_PERFORMANCE: PerformanceMetric[] = [
  { label: "Code Quality", value: 96, color: "bg-success" },
  { label: "Test Coverage", value: 91, color: "bg-success" },
  { label: "Task Success", value: 94, color: "bg-primary" },
  { label: "Speed (vs avg)", value: 88, color: "bg-primary" },
  { label: "Cost Efficiency", value: 92, color: "bg-success" },
];

export const MOCK_REVIEW_SUMMARY: ReviewSummary = {
  avgScore: 4.7,
  totalReviews: 89,
  distribution: [68, 22, 7, 2, 1],
};

export const MOCK_TASKS: Task[] = [
  {
    id: "TASK-0042",
    title: "Write unit tests for login flow",
    description:
      "Generate comprehensive unit tests for the authentication login flow covering valid credentials, invalid inputs, token refresh, rate limiting, and SQL injection prevention.",
    status: "running",
    priority: "high",
    agentId: "coder",
    agentName: "Coder",
    agentInitials: "C",
    agentGradientFrom: "#3B82F6",
    agentGradientTo: "#2563EB",
    createdAt: "47s",
    duration: null,
    cost: 1.2,
    budgetCap: 50,
    tokens: null,
    progress: 65,
    liveStatus: "Analysing codebase structure...",
    errorMessage: null,
    retries: 0,
    maxRetries: 3,
    rating: null,
  },
  {
    id: "TASK-0041",
    title: "Research best practices for rate limiting in FastAPI",
    description: "Research and compile best practices for implementing rate limiting in FastAPI.",
    status: "running",
    priority: "medium",
    agentId: "research",
    agentName: "Research",
    agentInitials: "R",
    agentGradientFrom: "#8B5CF6",
    agentGradientTo: "#6D28D9",
    createdAt: "1m 22s",
    duration: null,
    cost: 0.6,
    budgetCap: 20,
    tokens: null,
    progress: 40,
    liveStatus: "Searching web for recent articles...",
    errorMessage: null,
    retries: 0,
    maxRetries: 3,
    rating: null,
  },
  {
    id: "TASK-0040",
    title: "Generate API documentation for billing endpoints",
    description: "Generate API documentation for billing endpoints.",
    status: "queued",
    priority: "high",
    agentId: "research",
    agentName: "Research",
    agentInitials: "R",
    agentGradientFrom: "#8B5CF6",
    agentGradientTo: "#6D28D9",
    createdAt: "2m ago",
    duration: null,
    cost: null,
    budgetCap: 30,
    tokens: null,
    progress: null,
    liveStatus: null,
    errorMessage: null,
    retries: 0,
    maxRetries: 3,
    rating: null,
  },
  {
    id: "TASK-0039",
    title: "Write integration tests for payment webhook handler",
    description: "Write integration tests for payment webhook handler.",
    status: "queued",
    priority: "medium",
    agentId: "coder",
    agentName: "Coder",
    agentInitials: "C",
    agentGradientFrom: "#3B82F6",
    agentGradientTo: "#2563EB",
    createdAt: "5m ago",
    duration: null,
    cost: null,
    budgetCap: 50,
    tokens: null,
    progress: null,
    liveStatus: null,
    errorMessage: null,
    retries: 0,
    maxRetries: 3,
    rating: null,
  },
  {
    id: "TASK-0038",
    title: "Summarise competitor pricing page changes",
    description: "Summarise competitor pricing page changes.",
    status: "queued",
    priority: "low",
    agentId: "research",
    agentName: "Research",
    agentInitials: "R",
    agentGradientFrom: "#8B5CF6",
    agentGradientTo: "#6D28D9",
    createdAt: "12m ago",
    duration: null,
    cost: null,
    budgetCap: 15,
    tokens: null,
    progress: null,
    liveStatus: null,
    errorMessage: null,
    retries: 0,
    maxRetries: 3,
    rating: null,
  },
  {
    id: "TASK-0037",
    title: "Fix authentication token refresh bug",
    description: "Fix authentication token refresh bug.",
    status: "completed",
    priority: "high",
    agentId: "coder",
    agentName: "Coder",
    agentInitials: "C",
    agentGradientFrom: "#3B82F6",
    agentGradientTo: "#2563EB",
    createdAt: "14m ago",
    duration: "45s",
    cost: 1.8,
    budgetCap: 50,
    tokens: 14200,
    progress: 100,
    liveStatus: null,
    errorMessage: null,
    retries: 0,
    maxRetries: 3,
    rating: 5,
  },
  {
    id: "TASK-0036",
    title: "Investigate memory leak in Celery worker pool",
    description: "Investigate memory leak in Celery worker pool.",
    status: "completed",
    priority: "medium",
    agentId: "research",
    agentName: "Research",
    agentInitials: "R",
    agentGradientFrom: "#8B5CF6",
    agentGradientTo: "#6D28D9",
    createdAt: "1h ago",
    duration: "2m 10s",
    cost: 3.4,
    budgetCap: 30,
    tokens: 22800,
    progress: 100,
    liveStatus: null,
    errorMessage: null,
    retries: 0,
    maxRetries: 3,
    rating: 4,
  },
  {
    id: "TASK-0035",
    title: "Draft weekly team standup summary from Slack",
    description: "Draft weekly team standup summary from Slack.",
    status: "completed",
    priority: "low",
    agentId: "research",
    agentName: "Research",
    agentInitials: "R",
    agentGradientFrom: "#8B5CF6",
    agentGradientTo: "#6D28D9",
    createdAt: "3h ago",
    duration: "32s",
    cost: 0.4,
    budgetCap: 10,
    tokens: 5100,
    progress: 100,
    liveStatus: null,
    errorMessage: null,
    retries: 0,
    maxRetries: 3,
    rating: 5,
  },
  {
    id: "TASK-0034",
    title: "Deploy staging environment to Azure Container Apps",
    description: "Deploy staging environment to Azure Container Apps.",
    status: "failed",
    priority: "high",
    agentId: "coder",
    agentName: "Coder",
    agentInitials: "C",
    agentGradientFrom: "#3B82F6",
    agentGradientTo: "#2563EB",
    createdAt: "2h ago",
    duration: "4m 58s",
    cost: 52.1,
    budgetCap: 50,
    tokens: null,
    progress: null,
    liveStatus: null,
    errorMessage: "BudgetExceededError: Task cost $52.10 exceeded $50.00 limit",
    retries: 2,
    maxRetries: 3,
    rating: null,
  },
  {
    id: "TASK-0033",
    title: "Scrape pricing data from competitor websites",
    description: "Scrape pricing data from competitor websites.",
    status: "failed",
    priority: "medium",
    agentId: "research",
    agentName: "Research",
    agentInitials: "R",
    agentGradientFrom: "#8B5CF6",
    agentGradientTo: "#6D28D9",
    createdAt: "5h ago",
    duration: "30s",
    cost: 0.2,
    budgetCap: 20,
    tokens: null,
    progress: null,
    liveStatus: null,
    errorMessage: "ToolExecutionError: WebSearchTool timed out after 30s",
    retries: 3,
    maxRetries: 3,
    rating: null,
  },
];

export const MOCK_TASK_DETAIL_METRICS: TaskMetric[] = [
  {
    label: "Duration",
    value: "1m 07s",
    detail: "Queued: 3s \u00B7 Exec: 64s",
    iconBg: "bg-success/10",
    iconColor: "text-success",
  },
  {
    label: "Total Cost",
    value: "$2.50",
    detail: "LLM: $2.15 \u00B7 Tools: $0.35",
    iconBg: "bg-primary/10",
    iconColor: "text-primary",
  },
  {
    label: "Tokens",
    value: "18,200",
    detail: "In: 6,400 \u00B7 Out: 11,800",
    iconBg: "bg-[#8B5CF6]/10",
    iconColor: "text-[#8B5CF6]",
  },
  {
    label: "Tool Calls",
    value: "7",
    detail: "code_interpreter: 4 \u00B7 github: 3",
    iconBg: "bg-warning/10",
    iconColor: "text-warning",
  },
  {
    label: "LLM Model",
    value: "Claude Sonnet 4.6",
    detail: "via LiteLLM \u00B7 No fallback",
    iconBg: "bg-[#EC4899]/10",
    iconColor: "text-[#EC4899]",
  },
  {
    label: "Retries",
    value: "0 / 3",
    detail: "First attempt succeeded",
    iconBg: "bg-[#14B8A6]/10",
    iconColor: "text-[#14B8A6]",
  },
];

export const MOCK_TIMELINE: TimelineEntry[] = [
  { label: "Task queued", timestamp: "10:30:02", detail: "Priority: High \u00B7 Budget: $50.00", dotColor: "bg-neutral" },
  { label: "Agent initialised", timestamp: "10:30:05", detail: "Coder v1.2 \u00B7 Claude Sonnet 4.6 \u00B7 3 tools loaded", dotColor: "bg-primary" },
  { label: "Tool: code_interpreter", timestamp: "10:30:16", detail: "python analyze_code.py --target auth/ \u00B7 0.8s \u00B7 $0.12", dotColor: "bg-warning" },
  { label: "Tool: code_interpreter", timestamp: "10:30:30", detail: "python generate_tests.py --module auth.login \u00B7 2.1s \u00B7 $0.08", dotColor: "bg-warning" },
  { label: "Tool: github_mcp", timestamp: "10:30:52", detail: 'Create PR #47: "Add auth login unit tests" \u00B7 1.2s \u00B7 $0.15', dotColor: "bg-warning" },
  { label: "Task completed", timestamp: "10:31:09", detail: "12 tests generated \u00B7 All passing \u00B7 Output validated by guardrails", dotColor: "bg-success" },
];

export const MOCK_COST_SEGMENTS: CostSegment[] = [
  { label: "Input tokens", amount: 0.87, percentage: 34.8, color: "bg-primary" },
  { label: "Output tokens", amount: 1.28, percentage: 51.2, color: "bg-[#8B5CF6]" },
  { label: "Tool execution", amount: 0.35, percentage: 14.0, color: "bg-warning" },
];

export const MOCK_KPIS: KpiData[] = [
  { label: "Total Tasks", value: "24", change: "+8 from last week", changeType: "positive" },
  { label: "Success Rate", value: "91.7%", change: "+2.3%", changeType: "positive" },
  { label: "Avg Duration", value: "1m 42s", change: "-12s faster", changeType: "positive" },
  { label: "Total Cost", value: "$58.40", change: "+$12.30", changeType: "negative" },
];
